language: python
python:
  - "2.6"
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install nose
# command to run tests
script:
  - cd tests && nosetests .
